import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./global.scss";
import { PrimeReactProvider } from 'primereact/api';
import Sitebar from "./components/Sitebar/Sitebar.components";
import 'primeicons/primeicons.css';
import Nav from "./components/Nav/Nav.components";
import NavMain from "./components/NavMain/NavMain.components";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <PrimeReactProvider>
          <div className="dart-wrapper">
            <Sitebar />
            <div className="dart-content">
              <Nav/>
              <NavMain/>
              <section className="main dart-section dart-overflov-unset mpt-0" >
                <div className="dart_container mp-0">
                    {children}
                </div>
              </section>
            </div>
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
